name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List contents after checkout
      run: ls -la

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install --prefix wp-content/themes/twentytwentyone

    - name: Install Sass
      run: npm install sass --prefix wp-content/themes/twentytwentyone

    - name: Install rtlcss
      run: npm install rtlcss --prefix wp-content/themes/twentytwentyone

    - name: Install postcss
      run: npm install postcss --prefix wp-content/themes/twentytwentyone

    - name: Build theme assets
      run: |
        ./wp-content/themes/twentytwentyone/node_modules/.bin/sass wp-content/themes/twentytwentyone/assets/sass/style.scss:wp-content/themes/twentytwentyone/style.css --style=expanded --source-map
        ./wp-content/themes/twentytwentyone/node_modules/.bin/rtlcss wp-content/themes/twentytwentyone/style.css wp-content/themes/twentytwentyone/style-rtl.css
        # Add similar commands for other build steps

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Start SSH Agent & Setting up private key
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh-add deploy_key.pem

    - name: Check current directory
      run: pwd && ls -la 

    - name: Deploy to server using Rsync
      run: |
        rsync -av --exclude='.git/' --exclude='deploy_key.pem' -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/ ubuntu@54.93.51.234:/var/www/html/

