name: WordPress Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directory contents (for debugging)
      run: ls -la

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install theme dependencies
      run: npm install --prefix wp-content/themes/twentytwentyone

    - name: Build CSS
      run: ./wp-content/themes/twentytwentyone/node_modules/.bin/sass wp-content/themes/twentytwentyone/assets/sass/style.scss:wp-content/themes/twentytwentyone/style.css --style=expanded --source-map

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wordpress-files
        path: /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download production artifacts
      uses: actions/download-artifact@v2
      with:
        name: wordpress-files
        path: /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/

    - name: List directory contents (for debugging)
      run: ls -la /home/runner/work/wordpress-deployment-test/wordpress-deployment-test

    - name: Deploy to server
      run: |
        rsync -avv --exclude='.git/' --exclude='deploy_key.pem' -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/ ubuntu@54.93.51.234:/var/www/html/


