name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List contents after checkout
      run: ls -la /home/runner/work/wordpress-deployment-test/wordpress-deployment-test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install --prefix /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone

    - name: Install Sass
      run: npm install sass --prefix /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone

    - name: Install rtlcss
      run: npm install rtlcss --prefix /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone

    - name: Install postcss
      run: npm install postcss --prefix /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone

    - name: Build theme assets
      run: |
        /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone/node_modules/.bin/sass /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone/assets/sass/style.scss:/home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone/style.css --style=expanded --source-map
        /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone/node_modules/.bin/rtlcss /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone/style.css /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/wp-content/themes/twentytwentyone/style-rtl.css

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Setup SSH Key for Deployment
      run: |
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        eval "$(ssh-agent -s)"
        ssh-add deploy_key.pem

    - name: Check current directory and repository contents
      run: pwd && ls -la /home/runner/work/wordpress-deployment-test/wordpress-deployment-test

    - name: Deploy to server using Rsync
      run: |
        rsync -avv --exclude='.git/' --exclude='deploy_key.pem' -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" /home/runner/work/wordpress-deployment-test/wordpress-deployment-test/ ubuntu@54.93.51.234:/var/www/html/

